name: Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install beautifulsoup4 requests time json

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add data.json
        git commit -m "Update"
        git push
